FORMAT: 1A

# Parameters API
In this installment of the API Blueprint course we will discuss how to describe URI parameters.

But first let's add more messages to our system. For that we would need
introduce an message identifier – id. This id will be our parameter when
communicating with our API about messages.

# Data Structures

## storeGentofte (object)
+ id: 1 (number, required)
+ name: Gentofte (string)
+ address
+ opening_hours
+ phone
+ google_maps
+ products (array[chair])

## storeOslo (object)
+ id: 2 (number, required)
+ text: Oslo (string)
+ user (Kurt) - Author of the blog post.

## chair (object)
+ product_type: chair
+ sizes: medium
+ colors: red
+ availability: available
+ description: pretty cool chair
+ photos: url
+ assemble_guide_link: url


## chairFB (object)

+ title:"Classic White T-Shirt",
+ image_url:"http://petersapparel.parseapp.com/img/item100-thumb.png",
+ subtitle:"Soft white cotton t-shirt is back in style",
+ buttons:[
    {
      + type: "web_url",
      + url: "https://petersapparel.parseapp.com/view_item?item_id=100",
      + title: "View Item"
    }
  ]
}

## Boba (object)
+ name: Boba Fett
+ email: fett@intergalactic.com

## Kurt (object)
+ name: Kurt Ravn
+ email: fett@intergalactic.com


# stores [/stores]

## Retrieve all stores [GET]
+ Response 200 (application/json)
    + Attributes (array[storeGentofte,storeOslo ])

# gentofte [/stores/gentofte]

## Retrieve gentofte [GET]
+ Response 200 (application/json)
    + Attributes (storeGentofte)

## Retrieve gentofte [/stores/gentofte/fb]
+ Response 200 (application/json)
    + Attributes (storeGentofteFB)

# products/chairs [/products/fb/chairs/]
## Retrieve chair [GET]
+ Response 200 (application/json)
    
        {
            "messages": [
                {
                  "attachment":{
                    "type":"template",
                    "payload":{
                      "template_type":"generic",
                      "elements":[
                        {
                          "title":"STRANDMON | £179 ",
                          "image_url": "http://www.ikea.com/gb/en/images/products/strandmon-wing-chair-skiftebo-yellow__0325450_pe517970_s4.jpg",
                          "subtitle": "You can really loosen up and relax in comfort because the high back on this chair provides extra support for your neck.",
                          "buttons":[
                            {
                              "type":"web_url",
                              "url":"http://www.ikea.com",
                              "title":"View Item"
                            },{
                                "type": "element_share"
                            }
                          ]
                        },{
                          "title":"POÄNG | £55",
                          "image_url": "http://www.ikea.com/gb/en/images/products/po%C3%A4ng-armchair-birch-veneer-ransta-natural__19488_pe104775_s4.jpg",
                          "subtitle": "Layer-glued bent birch frame gives comfortable resilience.",
                          "buttons":[
                            {
                              "type":"web_url",
                              "url":"http://www.ikea.com",
                              "title":"View Item"
                            },{
                                "type": "element_share"
                            }
                          ]
                        },{
                          "title":"KULLABERG | £49",
                          "image_url": "http://www.ikea.com/gb/en/images/products/kullaberg-swivel-chair-pine-black__0410020_pe577748_s4.jpg",
                          "subtitle": "A desk chair inspired by old-fashioned industrial-style chairs, complete with modern functions.",
                          "buttons":[
                            {
                              "type":"web_url",
                              "url":"http://www.ikea.com",
                              "title":"View Item"
                            },{
                                "type": "element_share"
                            }
                          ]
                        }
                      ]
                    }
                  }
                }
            ]
        }
    

# products/chairs/red [/products/fb/chairs/red]
## Retrieve red chair [GET]
+ Response 200 (application/json)

        {
            "messages": [
                {
                  "attachment":{
                    "type":"template",
                    "payload":{
                      "template_type":"generic",
                      "elements":[
                        {
                          "title":"POÄNG | £100 ",
                          "image_url": "http://www.ikea.com/gb/en/images/products/po%C3%A4ng-rocking-chair-oak-veneer-ransta-red__0138472_pe297885_s4.jpg",
                          "subtitle": "The frame is made of layer-glued bent birch which is a very strong and durable material.",
                          "buttons":[
                            {
                              "type":"web_url",
                              "url":"http://www.ikea.com",
                              "title":"View Item"
                            },{
                                "type": "element_share"
                            }
                          ]
                        },{
                          "title":"SKÅLBERG/SPORREN | £25",
                          "image_url": "http://www.ikea.com/gb/en/images/products/sk%C3%A5lberg-sporren-swivel-chair-red-black__0309046_pe428450_s4.jpg",
                          "subtitle": "Your back gets support and extra relief from the built-in lumbar support.",
                          "buttons":[
                            {
                              "type":"web_url",
                              "url":"http://www.ikea.com",
                              "title":"View Item"
                            },{
                                "type": "element_share"
                            }
                          ]
                        },{
                          "title":"HENRIKSDAL | £25",
                          "image_url": "http://www.ikea.com/gb/en/images/products/henriksdal-chair-cover-long-mobacka-red-beige__0372055_pe551321_s4.jpg",
                          "subtitle": "The washable cover to HENRIKSDAL chair frame is easy to put on and take off.",
                          "buttons":[
                            {
                              "type":"web_url",
                              "url":"http://www.ikea.com",
                              "title":"View Item"
                            },{
                                "type": "element_share"
                            }
                          ]
                        }
                      ]
                    }
                  }
                }
            ]
        }


## a messge [/messages/{id}]

+ Parameters
    + id (number) - The ID of the desired coupon.

### Retrieve a Message [GET]

+ Response 200 (application/json)

            {
              "id": 1,
              "message": "Gentofte"
            }
            
            {
              "id": 2,
              "message": "Valby"
            }



## All stores [/stores{?limit}]
A resource representing all of my messages in the system.


### Retrieve all stores [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `20`

+ Response 200 (application/json)

        [
          {
            "id": 1,
            "message": "Hello World!"
          },
          {
            "id": 2,
            "message": "Time is an illusion. Lunchtime doubly so."
          },
          {
            "id": 3,
            "message": "So long, and thanks for all the fish."
          }
        ]